import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { 
  Play, 
  Heart, 
  Users, 
  Clock, 
  MoreVertical, 
  Share2,
  Shuffle,
  Edit,
  Lock,
  Globe,
  Download,
  Plus
} from 'lucide-react';

interface EnhancedPlaylistCardProps {
  playlist: {
    _id: string;
    name: string;
    description?: string;
    coverImageUrl?: string;
    trackIds: string[];
    isPublic: boolean;
    isAutoGenerated: boolean;
    generationConfig?: any;
    playCount: number;
    tags: string[];
    userId: string;
    createdAt: string;
    updatedAt: string;
  };
  variant?: 'default' | 'compact' | 'featured' | 'collaborative';
  showActions?: boolean;
  onPlay?: () => void;
  onEdit?: () => void;
  onShare?: () => void;
}

export const EnhancedPlaylistCard: React.FC<EnhancedPlaylistCardProps> = ({ 
  playlist, 
  variant = 'default',
  showActions = true,
  onPlay,
  onEdit,
  onShare
}) => {
  const [showMenu, setShowMenu] = useState(false);
  const [isLiked, setIsLiked] = useState(false);

  const formatDuration = (trackIds: string[]) => {
    const totalTracks = trackIds.length;
    return totalTracks === 1 ? '1 piste' : `${totalTracks} pistes`;
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('fr-FR', {
      month: 'short',
      day: 'numeric',
      year: 'numeric'
    });
  };

  const getPlaylistTypeColor = (playlist: any) => {
    if (playlist.isAutoGenerated) {
      return '#8B5CF6'; // Blue for auto-generated
    }
    if (playlist.tags?.includes('collaborative')) {
      return '#10B981'; // Green for collaborative
    }
    return '#FF6B35'; // Orange for user-created
  };

  const getPlaylistTypeIcon = (playlist: any) => {
    if (playlist.isAutoGenerated) {
      return <Shuffle className="w-4 h-4" />;
    }
    if (playlist.tags?.includes('collaborative')) {
      return <Users className="w-4 h-4" />;
    }
    return <Plus className="w-4 h-4" />;
  };

  const handleLike = async () => {
    setIsLiked(!isLiked);
    // TODO: Implement API call
    console.log('Toggle like for playlist:', playlist._id);
  };

  if (variant === 'compact') {
    return (
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0 }}
        className="flex items-center gap-3 p-3 bg-gray-900 rounded-lg hover:bg-gray-800 transition-colors border border-gray-800 cursor-pointer"
        onClick={onPlay}
      >
        <div className="relative w-12 h-12 rounded-lg overflow-hidden flex-shrink-0">
          {playlist.coverImageUrl ? (
            <img
              src={playlist.coverImageUrl}
              alt={playlist.name}
              className="w-full h-full object-cover"
            />
          ) : (
            <div 
              className="w-full h-full flex items-center justify-center"
              style={{ backgroundColor: getPlaylistTypeColor(playlist) }}
            >
              {getPlaylistTypeIcon(playlist)}
            </div>
          )}
        </div>
        
        <div className="flex-1 min-w-0">
          <h4 className="font-medium text-white text-sm truncate mb-1">
            {playlist.name}
          </h4>
          <div className="flex items-center gap-2 text-xs text-gray-400">
            <span>{formatDuration(playlist.trackIds)}</span>
            <span>{formatDate(playlist.createdAt)}</span>
          </div>
        </div>
        
        {showActions && (
          <button
            onClick={() => setShowMenu(!showMenu)}
            className="p-1 hover:bg-gray-700 rounded-lg transition-colors"
          >
            <MoreVertical className="w-4 h-4 text-gray-400" />
          </button>
        )}
      </motion.div>
    );
  }

  if (variant === 'featured') {
    return (
      <motion.div
        initial={{ opacity: 0, scale: 0.9 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.5 }}
        className="group relative bg-gradient-to-br from-gray-900 to-gray-800 rounded-xl overflow-hidden hover:from-gray-800 hover:to-gray-700 transition-all duration-300 border border-gray-700 hover:border-orange-500/50"
      >
        {/* Cover Image */}
        <div className="relative h-48 overflow-hidden">
          {playlist.coverImageUrl ? (
            <img
              src={playlist.coverImageUrl}
              alt={playlist.name}
              className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
            />
          ) : (
            <div 
              className="w-full h-full flex items-center justify-center"
              style={{ backgroundColor: getPlaylistTypeColor(playlist) }}
            >
              {getPlaylistTypeIcon(playlist)}
            </div>
          )}
          
          {/* Type Badge */}
          <div className="absolute top-3 left-3">
            <div className="flex items-center gap-1.5 px-2 py-1 bg-black/60 backdrop-blur-sm rounded-full">
              {getPlaylistTypeIcon(playlist)}
              <span className="text-xs text-white font-medium">
                {playlist.isAutoGenerated ? 'Auto' : playlist.tags?.includes('collaborative') ? 'Collaborative' : 'Personnelle'}
              </span>
            </div>
          </div>
        </div>

        {/* Content */}
        <div className="p-4">
          <h2 className="font-bold text-white text-lg mb-2 line-clamp-2 group-hover:text-orange-400 transition-colors">
            {playlist.name}
          </h2>
          
          {playlist.description && (
            <p className="text-gray-300 text-sm mb-3 line-clamp-2">
              {playlist.description}
            </p>
          )}

          {/* Stats */}
          <div className="flex items-center justify-between text-sm text-gray-400 mb-3">
            <div className="flex items-center gap-3">
              <div className="flex items-center gap-1">
                <Play className="w-4 h-4" />
                <span>{formatDuration(playlist.trackIds)}</span>
              </div>
              <div className="flex items-center gap-1">
                <Clock className="w-4 h-4" />
                <span>{formatDate(playlist.createdAt)}</span>
              </div>
              <div className="flex items-center gap-1">
                <Users className="w-4 h-4" />
                <span>{playlist.playCount || 0}</span>
              </div>
            </div>
            
            <div className="flex items-center gap-2">
              <button
                onClick={handleLike}
                className="p-1.5 hover:bg-gray-700 rounded-full transition-colors"
              >
                <Heart className={`w-4 h-4 ${isLiked ? 'fill-red-500 text-red-500' : 'text-gray-400'}`} />
              </button>
              
              {showActions && (
                <button
                  onClick={() => setShowMenu(!showMenu)}
                  className="p-1.5 hover:bg-gray-700 rounded-full transition-colors"
                >
                  <MoreVertical className="w-4 h-4 text-gray-400" />
                </button>
              )}
            </div>
          </div>

          {/* Tags */}
          {playlist.tags && playlist.tags.length > 0 && (
            <div className="flex flex-wrap gap-1.5">
              {playlist.tags.slice(0, 3).map((tag, index) => (
                <span 
                  key={index}
                  className="px-2 py-0.5 bg-gray-800 rounded-full text-xs text-gray-300"
                >
                  #{tag}
                </span>
              ))}
              {playlist.tags.length > 3 && (
                <span className="px-2 py-0.5 bg-gray-800 rounded-full text-xs text-gray-300">
                  +{playlist.tags.length - 3}
                </span>
              )}
            </div>
          )}
        </div>
      </motion.div>
    );
  }

  if (variant === 'collaborative') {
    return (
      <motion.div
        initial={{ opacity: 0, x: -20 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ delay: 0 }}
        className="group relative bg-gray-900 rounded-lg overflow-hidden hover:bg-gray-800 transition-all duration-200 border border-gray-800 hover:border-green-500/50"
      >
        <div className="flex items-center gap-3 p-4">
          {/* Collaborative Icon */}
          <div className="relative w-12 h-12 rounded-lg overflow-hidden flex-shrink-0">
            <div className="w-full h-full bg-gradient-to-br from-green-500 to-green-600 flex items-center justify-center">
              <Users className="w-6 h-6 text-white" />
            </div>
          </div>
          
          <div className="flex-1 min-w-0">
            <h4 className="font-medium text-white text-sm truncate mb-1 flex items-center gap-2">
              {playlist.name}
              <div className="flex items-center gap-1 px-2 py-0.5 bg-green-500/20 rounded-full">
                <Users className="w-3 h-3 text-green-400" />
                <span className="text-xs text-green-400">Collaborative</span>
              </div>
            </h4>
            
            <div className="flex items-center gap-3 text-xs text-gray-400">
              <span>{formatDuration(playlist.trackIds)}</span>
              <span>{playlist.trackIds.length} contributeurs</span>
              <span>Modifié {formatDate(playlist.updatedAt)}</span>
            </div>
          </div>
          
          {showActions && (
            <button
              onClick={() => setShowMenu(!showMenu)}
              className="p-1 hover:bg-gray-700 rounded-lg transition-colors"
            >
              <MoreVertical className="w-4 h-4 text-gray-400" />
            </button>
          )}
        </div>
      </motion.div>
    );
  }

  // Default variant
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0 }}
      className="group relative bg-gray-900 rounded-lg overflow-hidden hover:bg-gray-800 transition-all duration-200 border border-gray-800 hover:border-orange-500/50"
    >
      {/* Cover Image */}
      <div className="relative h-40 overflow-hidden">
        {playlist.coverImageUrl ? (
          <img
            src={playlist.coverImageUrl}
            alt={playlist.name}
            className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
          />
        ) : (
          <div 
            className="w-full h-full flex items-center justify-center"
            style={{ backgroundColor: getPlaylistTypeColor(playlist) }}
          >
            {getPlaylistTypeIcon(playlist)}
          </div>
        )}
        
        {/* Type Badge */}
        <div className="absolute top-2 left-2">
          <div className="flex items-center gap-1.5 px-2 py-0.5 bg-black/60 backdrop-blur-sm rounded-full">
            {getPlaylistTypeIcon(playlist)}
            <span className="text-xs text-white font-medium">
              {playlist.isAutoGenerated ? 'Auto' : 'Personnelle'}
            </span>
          </div>
        </div>

        {/* Action Buttons Overlay */}
        <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300">
          <div className="absolute top-2 right-2 flex gap-2">
            {playlist.isPublic ? (
              <div className="w-6 h-6 bg-green-500/20 backdrop-blur-sm rounded-full flex items-center justify-center">
                <Globe className="w-3 h-3 text-green-400" />
              </div>
            ) : (
              <div className="w-6 h-6 bg-gray-500/20 backdrop-blur-sm rounded-full flex items-center justify-center">
                <Lock className="w-3 h-3 text-gray-400" />
              </div>
            )}
            
            {showActions && (
              <button
                onClick={() => setShowMenu(!showMenu)}
                className="w-6 h-6 bg-black/60 backdrop-blur-sm rounded-full flex items-center justify-center hover:bg-black/80 transition-colors"
              >
                <MoreVertical className="w-3 h-3 text-white" />
              </button>
            )}
          </div>
        </div>

        {/* Play Button */}
        <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
          <button
            onClick={onPlay}
            className="w-12 h-12 bg-orange-500 rounded-full flex items-center justify-center hover:bg-orange-600 transition-colors group-hover:scale-110"
          >
            <Play className="w-5 h-5 text-white ml-0.5" />
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="p-4">
        <h3 className="font-semibold text-white text-sm mb-2 line-clamp-2 group-hover:text-orange-400 transition-colors">
          {playlist.name}
        </h3>
        
        {playlist.description && (
          <p className="text-gray-400 text-xs mb-3 line-clamp-2">
            {playlist.description}
          </p>
        )}

        {/* Stats */}
        <div className="flex items-center justify-between text-xs text-gray-500 mb-3">
          <div className="flex items-center gap-3">
            <div className="flex items-center gap-1">
              <Play className="w-3 h-3" />
              <span>{formatDuration(playlist.trackIds)}</span>
            </div>
            <div className="flex items-center gap-1">
              <Clock className="w-3 h-3" />
              <span>{formatDate(playlist.createdAt)}</span>
            </div>
            <div className="flex items-center gap-1">
              <Users className="w-3 h-3" />
              <span>{playlist.playCount || 0}</span>
            </div>
          </div>
          
          <div className="flex items-center gap-2">
            <button
              onClick={handleLike}
              className="p-1 hover:bg-gray-700 rounded-full transition-colors"
            >
              <Heart className={`w-3 h-3 ${isLiked ? 'fill-red-500 text-red-500' : 'text-gray-400'}`} />
            </button>
            
            {showActions && (
              <div className="flex gap-1">
                {onEdit && (
                  <button
                    onClick={onEdit}
                    className="p-1 hover:bg-gray-700 rounded-full transition-colors"
                  >
                    <Edit className="w-3 h-3 text-gray-400" />
                  </button>
                )}
                
                {onShare && (
                  <button
                    onClick={onShare}
                    className="p-1 hover:bg-gray-700 rounded-full transition-colors"
                  >
                    <Share2 className="w-3 h-3 text-gray-400" />
                  </button>
                )}
              </div>
            )}
          </div>
        </div>

        {/* Tags */}
        {playlist.tags && playlist.tags.length > 0 && (
          <div className="flex flex-wrap gap-1">
            {playlist.tags.slice(0, 4).map((tag, index) => (
              <span 
                key={index}
                className="px-2 py-0.5 bg-gray-800 rounded-full text-xs text-gray-300"
              >
                #{tag}
              </span>
            ))}
            {playlist.tags.length > 4 && (
              <span className="px-2 py-0.5 bg-gray-800 rounded-full text-xs text-gray-300">
                +{playlist.tags.length - 4}
              </span>
            )}
          </div>
        )}
      </div>
    </motion.div>
  );
};
