import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Link } from 'react-router-dom';
import { 
  Plus, 
  Search, 
  Filter, 
  Grid3X3, 
  List, 
  Heart, 
  Share2, 
  Download,
  Edit,
  Trash2,
  Users,
  Clock,
  TrendingUp,
  Shuffle,
  Lock,
  Globe
} from 'lucide-react';
import { EnhancedPlaylistCard } from './EnhancedPlaylistCard';

interface Playlist {
  _id: string;
  name: string;
  description?: string;
  coverImageUrl?: string;
  trackIds: string[];
  isPublic: boolean;
  isAutoGenerated: boolean;
  generationConfig?: any;
  playCount: number;
  tags: string[];
  userId: string;
  createdAt: string;
  updatedAt: string;
}

interface PlaylistStats {
  totalPlaylists: number;
  totalTracks: number;
  totalPlayTime: number;
  mostPlayedPlaylist?: Playlist;
  recentlyCreated: Playlist[];
  collaborativePlaylists: Playlist[];
}

export const PlaylistManagementPage: React.FC = () => {
  const [playlists, setPlaylists] = useState<Playlist[]>([]);
  const [stats, setStats] = useState<PlaylistStats | null>(null);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedFilter, setSelectedFilter] = useState<'all' | 'user' | 'collaborative' | 'auto'>('all');
  const [viewMode, setViewMode] = useState<'grid' | 'list'>('grid');
  const [sortBy, setSortBy] = useState<'recent' | 'name' | 'tracks' | 'plays'>('recent');
  const [showCreateDialog, setShowCreateDialog] = useState(false);

  useEffect(() => {
    fetchPlaylists();
  }, []);

  const fetchPlaylists = async () => {
    try {
      setLoading(true);
      const token = localStorage.getItem('authToken');
      
      if (!token) {
        // Fetch public playlists only
        const response = await fetch('/api/playlist/public?page=1&limit=50');
        const data = await response.json();
        
        if (data.success) {
          setPlaylists(data.data.playlists || []);
        }
      } else {
        // Fetch user playlists
        const response = await fetch('/api/playlist/user?page=1&limit=50', {
          headers: {
            'Authorization': `Bearer ${token}`
          }
        });
        const data = await response.json();
        
        if (data.success) {
          setPlaylists(data.data.playlists || []);
          calculateStats(data.data.playlists || []);
        }
      }
    } catch (error) {
      console.error('Error fetching playlists:', error);
    } finally {
      setLoading(false);
    }
  };

  const calculateStats = (playlistData: Playlist[]) => {
    const totalPlaylists = playlistData.length;
    const totalTracks = playlistData.reduce((sum, pl) => sum + pl.trackIds.length, 0);
    const totalPlayTime = totalTracks * 3.5; // Average track length
    
    const mostPlayedPlaylist = playlistData.reduce((most, pl) => 
      (pl.playCount || 0) > (most.playCount || 0) ? pl : most
    , playlistData[0]);

    const recentlyCreated = playlistData
      .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
      .slice(0, 3);

    const collaborativePlaylists = playlistData.filter(pl => 
      pl.tags?.includes('collaborative')
    );

    setStats({
      totalPlaylists,
      totalTracks,
      totalPlayTime,
      mostPlayedPlaylist,
      recentlyCreated,
      collaborativePlaylists
    });
  };

  const handleCreatePlaylist = async (playlistData: {
    name: string;
    description: string;
    isPublic: boolean;
    tags: string[];
  }) => {
    try {
      const token = localStorage.getItem('authToken');
      if (!token) {
        window.location.href = '/login';
        return;
      }

      const response = await fetch('/api/playlist', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(playlistData)
      });

      const data = await response.json();
      if (data.success) {
        setShowCreateDialog(false);
        fetchPlaylists();
      }
    } catch (error) {
      console.error('Error creating playlist:', error);
    }
  };

  const handleDeletePlaylist = async (playlistId: string) => {
    try {
      const token = localStorage.getItem('authToken');
      if (!token) return;

      const response = await fetch(`/api/playlist/${playlistId}`, {
        method: 'DELETE',
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });

      if (response.ok) {
        setPlaylists(playlists.filter(pl => pl._id !== playlistId));
      }
    } catch (error) {
      console.error('Error deleting playlist:', error);
    }
  };

  const formatDuration = (minutes: number) => {
    const hours = Math.floor(minutes / 60);
    const mins = minutes % 60;
    return hours > 0 ? `${hours}h ${mins}min` : `${mins}min`;
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('fr-FR', {
      month: 'short',
      day: 'numeric',
      year: 'numeric'
    });
  };

  const filteredPlaylists = playlists.filter(playlist => {
    const matchesSearch = playlist.name.toLowerCase().includes(searchQuery.toLowerCase());
    
    if (!matchesSearch) return false;
    
    switch (selectedFilter) {
      case 'user':
        return !playlist.isAutoGenerated;
      case 'collaborative':
        return playlist.tags?.includes('collaborative');
      case 'auto':
        return playlist.isAutoGenerated;
      default:
        return true;
    }
  });

  const sortedPlaylists = [...filteredPlaylists].sort((a, b) => {
    switch (sortBy) {
      case 'recent':
        return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
      case 'name':
        return a.name.localeCompare(b.name);
      case 'tracks':
        return b.trackIds.length - a.trackIds.length;
      case 'plays':
        return (b.playCount || 0) - (a.playCount || 0);
      default:
        return 0;
    }
  });

  if (loading) {
    return (
      <div className="min-h-screen bg-black flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-orange-500"></div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-black text-white">
      {/* Header */}
      <div className="sticky top-0 z-40 bg-black/95 backdrop-blur-md border-b border-gray-800">
        <div className="container mx-auto px-4 py-4">
          <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
            {/* Title */}
            <div className="flex items-center gap-3">
              <h1 className="text-2xl font-bold text-white">Mes Playlists</h1>
              {stats && (
                <span className="text-sm text-gray-400">
                  ({stats.totalPlaylists} playlists)
                </span>
              )}
            </div>

            {/* Actions */}
            <div className="flex items-center gap-3 w-full lg:w-auto">
              {/* Search */}
              <div className="relative flex-1 lg:flex-initial">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
                <input
                  type="text"
                  placeholder="Rechercher des playlists..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="w-full lg:w-80 pl-10 pr-4 py-2 bg-gray-900 border border-gray-700 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:border-orange-500 focus:ring-1 focus:ring-orange-500/20"
                />
              </div>

              {/* Create Button */}
              <button
                onClick={() => setShowCreateDialog(true)}
                className="flex items-center gap-2 px-4 py-2 bg-orange-500 hover:bg-orange-600 rounded-lg transition-colors"
              >
                <Plus className="w-5 h-5" />
                Créer
              </button>
            </div>
          </div>

          {/* Filters and View Mode */}
          <div className="flex flex-col lg:flex-row gap-4 pb-4 border-b border-gray-800">
            {/* Filters */}
            <div className="flex items-center gap-2">
              <Filter className="w-5 h-5 text-gray-400" />
              <div className="flex gap-2">
                {['all', 'user', 'collaborative', 'auto'].map((filter) => (
                  <button
                    key={filter}
                    onClick={() => setSelectedFilter(filter as any)}
                    className={`px-3 py-1.5 rounded-full text-sm font-medium transition-colors ${
                      selectedFilter === filter
                        ? 'bg-orange-500 text-white'
                        : 'text-gray-400 hover:bg-gray-800 hover:text-white'
                    }`}
                  >
                    {filter === 'all' && 'Toutes'}
                    {filter === 'user' && 'Personnelles'}
                    {filter === 'collaborative' && 'Collaboratives'}
                    {filter === 'auto' && 'Automatiques'}
                  </button>
                ))}
              </div>
            </div>

            {/* View Mode */}
            <div className="flex items-center gap-2 ml-auto">
              <button
                onClick={() => setViewMode(viewMode === 'grid' ? 'list' : 'grid')}
                className="flex items-center gap-2 px-3 py-1.5 bg-gray-900 border border-gray-700 rounded-lg hover:bg-gray-800 transition-colors"
              >
                {viewMode === 'grid' ? <List className="w-4 h-4" /> : <Grid3X3 className="w-4 h-4" />}
                <span className="text-sm text-gray-400">
                  {viewMode === 'grid' ? 'Liste' : 'Grille'}
                </span>
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="container mx-auto px-4 py-6">
        {/* Stats Cards */}
        {stats && (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
            <div className="bg-gray-900 rounded-lg p-4">
              <div className="flex items-center gap-2 text-orange-400 mb-1">
                <TrendingUp className="w-5 h-5" />
                <span className="text-2xl font-semibold">
                  {stats.totalPlaylists}
                </span>
              </div>
              <div className="text-sm text-gray-400">Total playlists</div>
            </div>
            
            <div className="bg-gray-900 rounded-lg p-4">
              <div className="flex items-center gap-2 text-orange-400 mb-1">
                <Clock className="w-5 h-5" />
                <span className="text-2xl font-semibold">
                  {formatDuration(Math.floor(stats.totalPlayTime / 60))}
                </span>
              </div>
              <div className="text-sm text-gray-400">Temps d'écoute total</div>
            </div>
            
            <div className="bg-gray-900 rounded-lg p-4">
              <div className="flex items-center gap-2 text-orange-400 mb-1">
                <Users className="w-5 h-5" />
                <span className="text-2xl font-semibold">
                  {stats.collaborativePlaylists.length}
                </span>
              </div>
              <div className="text-sm text-gray-400">Playlists collaboratives</div>
            </div>
            
            <div className="bg-gray-900 rounded-lg p-4">
              <div className="flex items-center gap-2 text-orange-400 mb-1">
                <Shuffle className="w-5 h-5" />
                <span className="text-2xl font-semibold">
                  {stats.totalTracks}
                </span>
              </div>
              <div className="text-sm text-gray-400">Total pistes</div>
            </div>
          </div>
        )}

        {/* Playlists Grid/List */}
        {sortedPlaylists.length === 0 ? (
          <div className="text-center py-12">
            <div className="max-w-md mx-auto">
              <div className="w-20 h-20 bg-gray-800 rounded-full flex items-center justify-center mx-auto mb-4">
                <List className="w-8 h-8 text-gray-600" />
              </div>
              <h2 className="text-xl font-semibold text-white mb-2">
                {searchQuery ? 'Aucune playlist trouvée' : 'Aucune playlist'}
              </h2>
              <p className="text-gray-400 mb-6">
                {searchQuery 
                  ? `Aucun résultat pour "${searchQuery}". Essayez d'autres termes.`
                  : 'Créez votre première playlist pour commencer !'
                }
              </p>
              <button
                onClick={() => setShowCreateDialog(true)}
                className="px-6 py-2 bg-orange-500 hover:bg-orange-600 rounded-lg transition-colors"
              >
                <Plus className="w-5 h-5 mr-2" />
                Créer une playlist
              </button>
            </div>
          </div>
        ) : (
          <div className={viewMode === 'grid' ? 
            'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6' : 
            'space-y-4'
          }>
            {sortedPlaylists.map((playlist, index) => (
              <motion.div
                key={playlist._id}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
              >
                <EnhancedPlaylistCard
                  playlist={playlist}
                  variant={viewMode === 'grid' ? 'default' : 'compact'}
                  showActions={true}
                  onPlay={() => console.log('Play playlist:', playlist._id)}
                  onEdit={() => console.log('Edit playlist:', playlist._id)}
                  onShare={() => console.log('Share playlist:', playlist._id)}
                />
              </motion.div>
            ))}
          </div>
        )}
      </div>

      {/* Create Playlist Dialog */}
      <AnimatePresence>
        {showCreateDialog && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm"
            onClick={() => setShowCreateDialog(false)}
          >
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              className="bg-gray-900 rounded-xl p-6 max-w-md w-full mx-4 border border-gray-800"
              onClick={(e) => e.stopPropagation()}
            >
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-xl font-bold text-white">Créer une playlist</h2>
                <button
                  onClick={() => setShowCreateDialog(false)}
                  className="p-2 hover:bg-gray-800 rounded-lg transition-colors"
                >
                  ×
                </button>
              </div>

              <form onSubmit={(e) => {
                e.preventDefault();
                const formData = new FormData(e.currentTarget);
                handleCreatePlaylist({
                  name: formData.get('name') as string,
                  description: formData.get('description') as string,
                  isPublic: formData.get('isPublic') === 'true',
                  tags: (formData.get('tags') as string || '').split(',').map(t => t.trim()).filter(Boolean)
                });
              }}>
                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-300 mb-2">
                      Nom de la playlist *
                    </label>
                    <input
                      type="text"
                      name="name"
                      required
                      className="w-full px-3 py-2 bg-gray-800 border border-gray-700 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:border-orange-500 focus:ring-1 focus:ring-orange-500/20"
                      placeholder="Ma playlist préférée"
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-300 mb-2">
                      Description
                    </label>
                    <textarea
                      name="description"
                      rows={3}
                      className="w-full px-3 py-2 bg-gray-800 border border-gray-700 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:border-orange-500 focus:ring-1 focus:ring-orange-500/20"
                      placeholder="Découvrez ma sélection..."
                    />
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <label className="block text-sm font-medium text-gray-300 mb-2">
                        Visibilité
                      </label>
                      <div className="space-y-2">
                        <label className="flex items-center gap-2">
                          <input
                            type="radio"
                            name="isPublic"
                            value="false"
                            defaultChecked
                            className="text-orange-500 focus:ring-orange-500"
                          />
                          <span className="text-sm text-gray-300">Privée</span>
                        </label>
                        <label className="flex items-center gap-2">
                          <input
                            type="radio"
                            name="isPublic"
                            value="true"
                            className="text-orange-500 focus:ring-orange-500"
                          />
                          <span className="text-sm text-gray-300">Publique</span>
                        </label>
                      </div>
                    </div>

                    <div>
                      <label className="block text-sm font-medium text-gray-300 mb-2">
                        Tags (séparés par des virgules)
                      </label>
                      <input
                        type="text"
                        name="tags"
                        className="w-full px-3 py-2 bg-gray-800 border border-gray-700 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:border-orange-500 focus:ring-1 focus:ring-orange-500/20"
                        placeholder="musique, détente, workout..."
                      />
                    </div>
                  </div>
                </div>

                <div className="flex gap-3 pt-4 border-t border-gray-800">
                  <button
                    type="button"
                    onClick={() => setShowCreateDialog(false)}
                    className="flex-1 px-4 py-2 bg-gray-700 hover:bg-gray-600 rounded-lg transition-colors"
                  >
                    Annuler
                  </button>
                  <button
                    type="submit"
                    className="flex-1 px-4 py-2 bg-orange-500 hover:bg-orange-600 rounded-lg font-medium text-white transition-colors"
                  >
                    Créer
                  </button>
                </div>
              </form>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};
