import { Track } from '../stores/audioStore';

export interface TranscriptSegment {
  id: string;
  startTime: number; // in seconds
  endTime: number; // in seconds
  text: string;
  confidence?: number; // 0-1
  speaker?: string; // for multi-speaker audio
}

export interface AudioTranscript {
  id: string;
  trackId: string;
  language: string;
  segments: TranscriptSegment[];
  fullText: string;
  createdAt: string;
  updatedAt: string;
  isAutoGenerated: boolean;
  isEdited: boolean;
}

export interface TranscriptRequest {
  trackId: string;
  audioUrl: string;
  language: string;
  enableSpeakerDiarization?: boolean;
}

export interface TranscriptUpdate {
  id: string;
  segments: TranscriptSegment[];
  fullText: string;
  isEdited: boolean;
}

class AudioTranscriptService {
  private baseUrl = '/api/transcripts';

  /**
   * Generate transcript for audio track
   */
  async generateTranscript(request: TranscriptRequest): Promise<AudioTranscript> {
    try {
      const response = await fetch(`${this.baseUrl}/generate`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(request),
      });

      if (!response.ok) {
        throw new Error(`Failed to generate transcript: ${response.statusText}`);
      }

      return await response.json();
    } catch (error) {
      console.error('Error generating transcript:', error);
      throw error;
    }
  }

  /**
   * Get existing transcript for track
   */
  async getTranscript(trackId: string): Promise<AudioTranscript | null> {
    try {
      const response = await fetch(`${this.baseUrl}/track/${trackId}`);
      
      if (response.status === 404) {
        return null;
      }

      if (!response.ok) {
        throw new Error(`Failed to get transcript: ${response.statusText}`);
      }

      return await response.json();
    } catch (error) {
      console.error('Error getting transcript:', error);
      throw error;
    }
  }

  /**
   * Update transcript segments
   */
  async updateTranscript(update: TranscriptUpdate): Promise<AudioTranscript> {
    try {
      const response = await fetch(`${this.baseUrl}/${update.id}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(update),
      });

      if (!response.ok) {
        throw new Error(`Failed to update transcript: ${response.statusText}`);
      }

      return await response.json();
    } catch (error) {
      console.error('Error updating transcript:', error);
      throw error;
    }
  }

  /**
   * Delete transcript
   */
  async deleteTranscript(transcriptId: string): Promise<void> {
    try {
      const response = await fetch(`${this.baseUrl}/${transcriptId}`, {
        method: 'DELETE',
      });

      if (!response.ok) {
        throw new Error(`Failed to delete transcript: ${response.statusText}`);
      }
    } catch (error) {
      console.error('Error deleting transcript:', error);
      throw error;
    }
  }

  /**
   * Search within transcript
   */
  searchTranscript(transcript: AudioTranscript, query: string): TranscriptSegment[] {
    if (!query.trim()) {
      return transcript.segments;
    }

    const lowerQuery = query.toLowerCase();
    return transcript.segments.filter(segment =>
      segment.text.toLowerCase().includes(lowerQuery)
    );
  }

  /**
   * Get transcript at specific time
   */
  getSegmentAtTime(transcript: AudioTranscript, currentTime: number): TranscriptSegment | null {
    return transcript.segments.find(segment =>
      currentTime >= segment.startTime && currentTime <= segment.endTime
    ) || null;
  }

  /**
   * Format time for display
   */
  formatTime(seconds: number): string {
    const hours = Math.floor(seconds / 3600);
    const minutes = Math.floor((seconds % 3600) / 60);
    const secs = Math.floor(seconds % 60);

    if (hours > 0) {
      return `${hours}:${minutes.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
    }
    return `${minutes}:${secs.toString().padStart(2, '0')}`;
  }

  /**
   * Export transcript as SRT
   */
  exportToSRT(transcript: AudioTranscript): string {
    return transcript.segments
      .map((segment, index) => {
        const startTime = this.formatSRTTime(segment.startTime);
        const endTime = this.formatSRTTime(segment.endTime);
        
        return `${index + 1}\n${startTime} --> ${endTime}\n${segment.text}\n`;
      })
      .join('\n');
  }

  /**
   * Export transcript as plain text
   */
  exportToText(transcript: AudioTranscript): string {
    return transcript.segments
      .map(segment => segment.text)
      .join(' ');
  }

  /**
   * Format time for SRT format
   */
  private formatSRTTime(seconds: number): string {
    const hours = Math.floor(seconds / 3600);
    const minutes = Math.floor((seconds % 3600) / 60);
    const secs = Math.floor(seconds % 60);
    const milliseconds = Math.floor((seconds % 1) * 1000);

    return `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')},${milliseconds.toString().padStart(3, '0')}`;
  }

  /**
   * Mock transcript generation for development
   */
  async mockGenerateTranscript(track: Track): Promise<AudioTranscript> {
    // Simulate API delay
    await new Promise(resolve => setTimeout(resolve, 2000));

    const mockSegments: TranscriptSegment[] = [
      {
        id: '1',
        startTime: 0,
        endTime: 5,
        text: 'Bienvenue dans MAATFEED, votre plateforme culturelle africaine.',
        confidence: 0.95,
        speaker: 'Host'
      },
      {
        id: '2',
        startTime: 5,
        endTime: 12,
        text: 'Aujourd\'hui nous explorons les richesses de la musique africaine contemporaine.',
        confidence: 0.92,
        speaker: 'Host'
      },
      {
        id: '3',
        startTime: 12,
        endTime: 20,
        text: 'De l\'afrobeat aux rythmes traditionnels, découvrez un continent en mouvement.',
        confidence: 0.88,
        speaker: 'Host'
      },
      {
        id: '4',
        startTime: 20,
        endTime: 28,
        text: 'Rejoignez-nous dans ce voyage musical à travers les cultures et les générations.',
        confidence: 0.91,
        speaker: 'Host'
      },
      {
        id: '5',
        startTime: 28,
        endTime: 35,
        text: 'MAATFEED, où la culture africaine prend vie.',
        confidence: 0.94,
        speaker: 'Host'
      }
    ];

    return {
      id: `transcript-${track.id}`,
      trackId: track.id,
      language: 'fr',
      segments: mockSegments,
      fullText: mockSegments.map(s => s.text).join(' '),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      isAutoGenerated: true,
      isEdited: false
    };
  }
}

export const audioTranscriptService = new AudioTranscriptService();
