import { getJson, postJson } from "./httpClient";

export interface AudioTrack {
  id: string;
  title: string;
  artist: string;
  description?: string;
  mediaUrl: string;
  duration: number;
  coverImageUrl?: string;
  tags: string[];
  genre: string;
  contentId?: string;
  sourceProvider?: string;
  sourcePageUrl?: string;
  externalSourceId?: string;
  contextUrl?: string;
  contextTitle?: string;
  contextType?: "video" | "debate" | "article" | "reference" | null;
  playCount: number;
  createdAt: string;
  updatedAt: string;
  typeLabel?: "musique" | "meditation" | "discours" | "debat audio";
  shortTitle?: string;
  simpleDescription?: string;
  enrichedTags?: string[];
  categoryLabel?: string;
  highlightMoments?: Array<{
    label: string;
    timeSeconds: number;
  }>;
  context?: {
    contentId?: string;
    contentRoute?: string;
    debateRoute?: string;
    primaryRoute?: string;
    primaryHref?: string;
    isExternal?: boolean;
    primaryLabel?: string;
  } | null;
}

export interface Playlist {
  id: string;
  name: string;
  description?: string;
  userId: string;
  trackIds: string[];
  isPublic: boolean;
  isAutoGenerated: boolean;
  generationConfig?: any;
  playCount: number;
  tags: string[];
  createdAt: string;
  updatedAt: string;
}

export interface AudioResponse {
  success: boolean;
  data: AudioTrack[];
  meta: {
    count: number;
    timestamp: string;
  };
}

export interface PlaylistResponse {
  success: boolean;
  data: Playlist[];
  meta: {
    count: number;
    timestamp: string;
  };
}

export interface AudioDiscoverySection {
  id: "trending" | "for_you" | "learn" | "relax" | "viral";
  title: string;
  subtitle: string;
  tracks: AudioTrack[];
}

export interface AudioDiscoveryPayload {
  sections: AudioDiscoverySection[];
  featuredTrack: AudioTrack | null;
  sourceBlueprint: {
    keywords: string[];
    providers: string[];
    stats: {
      publishedAudioCount: number;
      curatedTrackCount: number;
      configuredFeedCount: number;
      configuredDirectCount: number;
      contextLinkedCount: number;
    };
  };
}

export async function getAudioTracks(limit = 50): Promise<AudioTrack[]> {
  const response = await getJson<AudioResponse>(`/api/audio/tracks?limit=${limit}`);
  return response.data;
}

export async function getPlaylists(): Promise<Playlist[]> {
  const response = await getJson<PlaylistResponse>("/api/audio/playlists");
  return response.data;
}

export async function createPlaylist(input: {
  name: string;
  description?: string;
  trackIds?: string[];
  isPublic?: boolean;
  tags?: string[];
}): Promise<Playlist> {
  const response = await postJson<{ success: boolean; data: Playlist; meta: { timestamp: string } }>("/api/audio/playlists", input);
  return response.data;
}

export async function getAutoPlaylist(config?: {
  genre?: string;
  minPlayCount?: number;
  limit?: number;
}): Promise<Playlist> {
  const params = new URLSearchParams();
  if (config?.genre) params.set("genre", config.genre);
  if (config?.minPlayCount) params.set("minPlayCount", config.minPlayCount.toString());
  if (config?.limit) params.set("limit", config.limit.toString());

  const url = `/api/audio/playlists/auto${params.toString() ? `?${params.toString()}` : ""}`;
  const response = await getJson<{ success: boolean; data: Playlist; meta: { timestamp: string } }>(url);
  return response.data;
}

export async function getAudioDiscovery(limit = 6): Promise<AudioDiscoveryPayload> {
  const response = await getJson<{ success: boolean; data: AudioDiscoveryPayload; meta: { timestamp: string } }>(
    `/api/audio/discovery?limit=${limit}`
  );
  return response.data;
}
