import { getJson } from "./httpClient";

export interface QuizQuestion {
  contentId: string;
  question: string;
  options: string[];
}

export interface QuizResponse {
  correct: boolean;
  explanation: string;
  feedback: string;
}

export interface RecapQuiz {
  contentIds: string[];
  contentTitles: string[];
  question: string;
  options: string[];
}

export async function getQuizQuestion(contentId: string): Promise<QuizQuestion | null> {
  try {
    const response = await getJson<{ data: QuizQuestion }>(
      `/api/learning/quiz/${contentId}`
    );
    return response?.data ?? null;
  } catch {
    return null;
  }
}

export async function submitQuizAnswer(
  contentId: string,
  answer: string,
  quiz: QuizQuestion
): Promise<QuizResponse> {
  const response = await getJson<{ data: QuizResponse }>(
    `/api/learning/quiz/${contentId}/answer`,
    {
      method: "POST",
      body: JSON.stringify({ answer, quiz })
    }
  );
  return response?.data ?? { correct: false, explanation: "", feedback: "" };
}

export async function getRecapQuiz(contentIds: string[]): Promise<RecapQuiz | null> {
  if (contentIds.length < 2) return null;
  try {
    const response = await getJson<{ data: RecapQuiz }>(
      `/api/learning/recap-quiz?contentIds=${contentIds.join(",")}`
    );
    return response?.data ?? null;
  } catch {
    return null;
  }
}

export async function submitRecapQuizAnswer(
  answer: string,
  quiz: RecapQuiz
): Promise<QuizResponse> {
  const response = await getJson<{ data: QuizResponse }>(
    `/api/learning/recap-quiz/answer`,
    {
      method: "POST",
      body: JSON.stringify({ answer, quiz })
    }
  );
  return response?.data ?? { correct: false, explanation: "", feedback: "" };
}

// ==================== AUTO-GENERATED QUIZZES ====================

export interface AutoQuizQuestion {
  id: string;
  question: string;
  options: string[];
  correctAnswerIndex: number;
  explanation: string;
  difficulty: "easy" | "medium" | "hard";
  conceptTested: string;
  contentId?: string;
}

export interface AutoGeneratedQuiz {
  contentId: string;
  questions: AutoQuizQuestion[];
  generatedAt: string;
  source: "transcript" | "summary" | "metadata";
  estimatedDifficulty: "beginner" | "intermediate" | "advanced";
}

export interface QuizSubmissionResult {
  score: number;
  correctCount: number;
  totalQuestions: number;
  results: Array<{
    questionId: string;
    correct: boolean;
    correctAnswer: number;
    explanation: string;
    conceptTested: string;
  }>;
  status: "new" | "learned" | "review";
  stats: {
    totalQuizzesTaken: number;
    averageScore: number;
    contentMastered: number;
    currentStreak: number;
  };
}

export interface UserQuizStats {
  totalQuizzesTaken: number;
  averageScore: number;
  contentMastered: number;
  currentStreak: number;
}

export async function getAutoQuiz(contentId: string, force: boolean = false): Promise<AutoGeneratedQuiz | null> {
  try {
    const response = await getJson<AutoGeneratedQuiz>(
      `/api/quiz/content/${contentId}${force ? "?force=true" : ""}`
    );
    return response;
  } catch {
    return null;
  }
}

export async function submitAutoQuiz(
  contentId: string,
  answers: Array<{ questionId: string; answerIndex: number }>
): Promise<QuizSubmissionResult | null> {
  try {
    const response = await getJson<QuizSubmissionResult>(`/api/quiz/content/${contentId}/submit`, {
      method: "POST",
      body: JSON.stringify({ answers })
    });
    return response;
  } catch {
    return null;
  }
}

export async function getUserQuizStats(): Promise<UserQuizStats | null> {
  try {
    return await getJson<UserQuizStats>("/api/quiz/stats");
  } catch {
    return null;
  }
}

export interface DailyChallenge {
  available: boolean;
  message?: string;
  questionCount?: number;
  questions?: AutoQuizQuestion[];
  contentCount?: number;
}

export async function getDailyChallenge(): Promise<DailyChallenge | null> {
  try {
    return await getJson<DailyChallenge>("/api/quiz/daily-challenge");
  } catch {
    return null;
  }
}
