import { useState, useEffect, useCallback } from "react";
import {
  getAutoQuiz,
  submitAutoQuiz,
  getUserQuizStats,
  getDailyChallenge,
  type AutoGeneratedQuiz,
  type QuizSubmissionResult,
  type UserQuizStats,
  type DailyChallenge
} from "../services/quizService";

interface UseAutoQuizResult {
  quiz: AutoGeneratedQuiz | null;
  loading: boolean;
  error: Error | null;
  loadQuiz: (force?: boolean) => Promise<void>;
  submitQuiz: (answers: Array<{ questionId: string; answerIndex: number }>) => Promise<QuizSubmissionResult | null>;
}

export function useAutoQuiz(contentId: string | undefined): UseAutoQuizResult {
  const [quiz, setQuiz] = useState<AutoGeneratedQuiz | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  const loadQuiz = useCallback(async (force: boolean = false) => {
    if (!contentId) {
      setLoading(false);
      return;
    }

    try {
      setLoading(true);
      setError(null);
      const data = await getAutoQuiz(contentId, force);
      setQuiz(data);
      if (!data) {
        setError(new Error("Could not load quiz for this content"));
      }
    } catch (err) {
      setError(err instanceof Error ? err : new Error("Failed to load quiz"));
    } finally {
      setLoading(false);
    }
  }, [contentId]);

  useEffect(() => {
    loadQuiz();
  }, [loadQuiz]);

  const submitQuiz = useCallback(async (
    answers: Array<{ questionId: string; answerIndex: number }>
  ): Promise<QuizSubmissionResult | null> => {
    if (!contentId) return null;
    return submitAutoQuiz(contentId, answers);
  }, [contentId]);

  return { quiz, loading, error, loadQuiz, submitQuiz };
}

interface UseQuizStatsResult {
  stats: UserQuizStats | null;
  loading: boolean;
  error: Error | null;
  refresh: () => Promise<void>;
}

export function useQuizStats(): UseQuizStatsResult {
  const [stats, setStats] = useState<UserQuizStats | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  const loadStats = useCallback(async () => {
    try {
      setLoading(true);
      setError(null);
      const data = await getUserQuizStats();
      setStats(data);
    } catch (err) {
      setError(err instanceof Error ? err : new Error("Failed to load stats"));
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadStats();
  }, [loadStats]);

  return { stats, loading, error, refresh: loadStats };
}

interface UseDailyChallengeResult {
  challenge: DailyChallenge | null;
  loading: boolean;
  error: Error | null;
  refresh: () => Promise<void>;
}

export function useDailyChallenge(): UseDailyChallengeResult {
  const [challenge, setChallenge] = useState<DailyChallenge | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  const loadChallenge = useCallback(async () => {
    try {
      setLoading(true);
      setError(null);
      const data = await getDailyChallenge();
      setChallenge(data);
    } catch (err) {
      setError(err instanceof Error ? err : new Error("Failed to load challenge"));
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadChallenge();
  }, [loadChallenge]);

  return { challenge, loading, error, refresh: loadChallenge };
}
