import mongoose from "mongoose";
import { createRequire } from "module";
import { UserModel } from "../../apps/api/src/models/User.js";
import { ProfileModel } from "../../apps/api/src/models/Profile.js";
import { SessionModel } from "../../apps/api/src/models/Session.js";
import { InteractionModel } from "../../apps/api/src/models/Interaction.js";
import { CommentModel } from "../../apps/api/src/models/Comment.js";
import { ReplyModel } from "../../apps/api/src/models/Reply.js";
import { NotificationModel } from "../../apps/api/src/models/Notification.js";
import { PasswordResetTokenModel } from "../../apps/api/src/models/PasswordResetToken.js";
import { EmailVerificationTokenModel } from "../../apps/api/src/models/EmailVerificationToken.js";
import { UserNotificationPreferencesModel } from "../../apps/api/src/models/UserNotificationPreferences.js";
import { FeedSnapshotModel } from "../../apps/api/src/models/FeedSnapshot.js";
import { PlaylistModel } from "../../apps/api/src/models/Playlist.js";
import { createRedisClient } from "../../apps/api/src/db/redis.js";

// Load environment variables from .env file
const require = createRequire(import.meta.url);
const dotenv = require("dotenv");
dotenv.config({ path: "../../apps/api/.env" });

// Email of the user to delete (CLI arg takes priority, then env var, then default)
const TARGET_EMAIL = process.argv[2] || process.env.TARGET_EMAIL || "kyfran6@gmail.com";

async function deleteUserByEmail(email: string) {
  console.log(`🔍 Searching for user with email: ${email}`);

  // Find user by email (case-insensitive)
  const user = await UserModel.findOne({ email: email.toLowerCase() });

  if (!user) {
    console.log(`❌ User with email "${email}" not found`);
    return false;
  }

  const userId = user._id;
  console.log(`✅ Found user: ${userId} (${user.email})`);
  console.log(`🗑️  Starting deletion of user data...\n`);

  const results: Record<string, number> = {};

  // 1. Delete Profile
  const profileResult = await ProfileModel.deleteOne({ userId });
  results["Profile"] = profileResult.deletedCount || 0;
  console.log(`  Profile: ${profileResult.deletedCount} deleted`);

  // 2. Delete Sessions
  const sessionResult = await SessionModel.deleteMany({ userId });
  results["Sessions"] = sessionResult.deletedCount || 0;
  console.log(`  Sessions: ${sessionResult.deletedCount} deleted`);

  // 3. Delete Interactions
  const interactionResult = await InteractionModel.deleteMany({ userId });
  results["Interactions"] = interactionResult.deletedCount || 0;
  console.log(`  Interactions: ${interactionResult.deletedCount} deleted`);

  // 4. Delete Comments
  const commentResult = await CommentModel.deleteMany({ userId });
  results["Comments"] = commentResult.deletedCount || 0;
  console.log(`  Comments: ${commentResult.deletedCount} deleted`);

  // 5. Delete Replies
  const replyResult = await ReplyModel.deleteMany({ userId });
  results["Replies"] = replyResult.deletedCount || 0;
  console.log(`  Replies: ${replyResult.deletedCount} deleted`);

  // 6. Delete Notifications
  const notificationResult = await NotificationModel.deleteMany({ userId });
  results["Notifications"] = notificationResult.deletedCount || 0;
  console.log(`  Notifications: ${notificationResult.deletedCount} deleted`);

  // 7. Delete Password Reset Tokens
  const pwdTokenResult = await PasswordResetTokenModel.deleteMany({ userId });
  results["PasswordResetTokens"] = pwdTokenResult.deletedCount || 0;
  console.log(`  PasswordResetTokens: ${pwdTokenResult.deletedCount} deleted`);

  // 8. Delete Email Verification Tokens
  const emailTokenResult = await EmailVerificationTokenModel.deleteMany({ userId });
  results["EmailVerificationTokens"] = emailTokenResult.deletedCount || 0;
  console.log(`  EmailVerificationTokens: ${emailTokenResult.deletedCount} deleted`);

  // 9. Delete User Notification Preferences
  const notifPrefResult = await UserNotificationPreferencesModel.deleteOne({ userId });
  results["NotificationPreferences"] = notifPrefResult.deletedCount || 0;
  console.log(`  NotificationPreferences: ${notifPrefResult.deletedCount} deleted`);

  // 10. Delete Feed Snapshots (user scope)
  const feedSnapshotResult = await FeedSnapshotModel.deleteMany({
    scope: "user",
    scopeId: userId.toString()
  });
  results["FeedSnapshots"] = feedSnapshotResult.deletedCount || 0;
  console.log(`  FeedSnapshots: ${feedSnapshotResult.deletedCount} deleted`);

  // 11. Delete User Playlists (not auto-generated)
  const playlistResult = await PlaylistModel.deleteMany({
    userId,
    isAutoGenerated: false
  });
  results["Playlists"] = playlistResult.deletedCount || 0;
  console.log(`  Playlists: ${playlistResult.deletedCount} deleted`);

  // 12. Finally, delete the User itself
  const userResult = await UserModel.deleteOne({ _id: userId });
  results["User"] = userResult.deletedCount || 0;
  console.log(`  User: ${userResult.deletedCount} deleted`);

  // Summary
  console.log(`\n📊 Deletion Summary:`);
  console.log(`====================`);
  const totalDeleted = Object.values(results).reduce((sum, count) => sum + count, 0);
  for (const [model, count] of Object.entries(results)) {
    if (count > 0) {
      console.log(`  ${model}: ${count}`);
    }
  }
  console.log(`\n✅ User "${email}" and all associated data deleted successfully!`);
  console.log(`   Total records deleted: ${totalDeleted}`);

  return true;
}

async function main() {
  let redisClient: ReturnType<typeof createRedisClient> | null = null;

  try {
    const mongoUri = process.env.MONGODB_URI || "mongodb://localhost:27017/maat-feed";

    console.log("🔗 Connecting to MongoDB...");
    await mongoose.connect(mongoUri);
    console.log("✅ Connected to MongoDB\n");

    console.log("🔗 Connecting to Redis...");
    try {
      redisClient = createRedisClient();
      if (redisClient.status === "wait") {
        await redisClient.connect();
      }
      console.log("✅ Connected to Redis\n");
    } catch (err) {
      console.log("⚠️  Redis connection failed (non-critical):", (err as Error).message);
      redisClient = null;
    }

    const deleted = await deleteUserByEmail(TARGET_EMAIL);

    await mongoose.disconnect();
    if (redisClient && redisClient.status === "ready") {
      await redisClient.quit();
    }
    console.log("\n👋 Disconnected from databases");

    process.exit(deleted ? 0 : 1);
  } catch (error) {
    console.error("❌ Error:", error);
    process.exit(1);
  }
}

main();
