import { AudioTrackModel } from "../models/AudioTrack.js";
import { PlaylistModel } from "../models/Playlist.js";
import { syncConfiguredAudioSources } from "./audioCatalogSyncService.js";

export interface AudioTrackData {
  id: string;
  title: string;
  artist: string;
  description?: string;
  mediaUrl: string;
  duration: number;
  coverImageUrl?: string;
  tags: string[];
  genre: string;
  contentId?: string;
  sourceProvider?: string;
  sourcePageUrl?: string;
  externalSourceId?: string;
  contextUrl?: string;
  contextTitle?: string;
  contextType?: "video" | "debate" | "article" | "reference" | null;
  playCount: number;
  createdAt: string;
  updatedAt: string;
}

export interface PlaylistData {
  id: string;
  name: string;
  description?: string;
  userId: string;
  trackIds: string[];
  isPublic: boolean;
  isAutoGenerated: boolean;
  generationConfig?: any;
  playCount: number;
  tags: string[];
  createdAt: string;
  updatedAt: string;
}

let audioCatalogBootstrapPromise: Promise<void> | null = null;

async function ensureAudioCatalogSeeded() {
  const trackCount = await AudioTrackModel.countDocuments({ isPublic: true });
  if (trackCount > 0) {
    return;
  }

  if (!audioCatalogBootstrapPromise) {
    audioCatalogBootstrapPromise = syncConfiguredAudioSources()
      .then(() => undefined)
      .catch((error) => {
        console.error("Audio catalog bootstrap failed:", error);
      })
      .finally(() => {
        audioCatalogBootstrapPromise = null;
      });
  }

  await audioCatalogBootstrapPromise;
}

export async function getAudioTracks(limit = 50): Promise<AudioTrackData[]> {
  await ensureAudioCatalogSeeded();

  const tracks = await AudioTrackModel.find({ isPublic: true })
    .sort({ playCount: -1, createdAt: -1 })
    .limit(limit)
    .populate("contentId")
    .lean();

  return tracks.map((track: any) => ({
    id: track._id.toString(),
    title: track.title,
    artist: track.artist,
    description: track.description,
    mediaUrl: track.mediaUrl,
    duration: track.duration,
    coverImageUrl: track.coverImageUrl,
    tags: track.tags || [],
    genre: track.genre,
    contentId: track.contentId?._id?.toString?.() || track.contentId?.toString?.(),
    sourceProvider: track.sourceProvider,
    sourcePageUrl: track.sourcePageUrl || undefined,
    externalSourceId: track.externalSourceId || undefined,
    contextUrl: track.contextUrl || undefined,
    contextTitle: track.contextTitle || undefined,
    contextType: track.contextType || null,
    playCount: track.playCount,
    createdAt: track.createdAt.toISOString(),
    updatedAt: track.updatedAt.toISOString()
  }));
}

export async function getPlaylists(userId?: string): Promise<PlaylistData[]> {
  await ensureAudioCatalogSeeded();

  const query = userId
    ? { $or: [{ userId }, { isAutoGenerated: true, isPublic: true }] }
    : { isPublic: true, isAutoGenerated: true };

  const playlists = await PlaylistModel.find(query)
    .sort({ playCount: -1, createdAt: -1 })
    .populate("trackIds")
    .lean();

  return playlists.map((playlist: any) => ({
    id: playlist._id.toString(),
    name: playlist.name,
    description: playlist.description,
    userId: playlist.userId?.toString() || "",
    trackIds: (playlist.trackIds || []).map((trackId: any) => trackId.toString()),
    isPublic: playlist.isPublic,
    isAutoGenerated: playlist.isAutoGenerated,
    generationConfig: playlist.generationConfig,
    playCount: playlist.playCount,
    tags: playlist.tags || [],
    createdAt: playlist.createdAt.toISOString(),
    updatedAt: playlist.updatedAt.toISOString()
  }));
}

export async function createPlaylist(input: {
  name: string;
  description?: string;
  userId: string;
  trackIds?: string[];
  isPublic?: boolean;
  tags?: string[];
}): Promise<PlaylistData> {
  const playlist = await PlaylistModel.create({
    name: input.name,
    description: input.description,
    userId: input.userId,
    trackIds: input.trackIds || [],
    isPublic: input.isPublic ?? false,
    tags: input.tags || []
  });

  return {
    id: playlist._id.toString(),
    name: playlist.name,
    description: playlist.description,
    userId: playlist.userId.toString(),
    trackIds: (playlist.trackIds || []).map((id: any) => id.toString()),
    isPublic: playlist.isPublic,
    isAutoGenerated: playlist.isAutoGenerated,
    generationConfig: playlist.generationConfig,
    playCount: playlist.playCount,
    tags: playlist.tags || [],
    createdAt: playlist.createdAt.toISOString(),
    updatedAt: playlist.updatedAt.toISOString()
  };
}

export async function generateAutoPlaylist(config: {
  genre?: string;
  minPlayCount?: number;
  limit?: number;
}): Promise<PlaylistData> {
  await ensureAudioCatalogSeeded();

  const limit = config.limit || 20;
  const minPlayCount = config.minPlayCount || 0;

  const trackQuery: any = { isPublic: true, playCount: { $gte: minPlayCount } };
  if (config.genre) {
    trackQuery.genre = config.genre;
  }

  const tracks = await AudioTrackModel.find(trackQuery)
    .sort({ playCount: -1, createdAt: -1 })
    .limit(limit)
    .lean();

  const playlistName = config.genre
    ? `Kemet ${config.genre.charAt(0).toUpperCase() + config.genre.slice(1)} Mix`
    : "Kemet Essentials";

  const existingPlaylist = await PlaylistModel.findOne({
    name: playlistName,
    isAutoGenerated: true,
    isPublic: true
  });

  if (existingPlaylist) {
    existingPlaylist.trackIds = tracks.map((track: any) => track._id);
    existingPlaylist.generationConfig = config;
    await existingPlaylist.save();

    return {
      id: existingPlaylist._id.toString(),
      name: existingPlaylist.name,
      description: existingPlaylist.description,
      userId: existingPlaylist.userId?.toString() || "",
      trackIds: (existingPlaylist.trackIds || []).map((id: any) => id.toString()),
      isPublic: existingPlaylist.isPublic,
      isAutoGenerated: existingPlaylist.isAutoGenerated,
      generationConfig: existingPlaylist.generationConfig,
      playCount: existingPlaylist.playCount,
      tags: existingPlaylist.tags || [],
      createdAt: existingPlaylist.createdAt.toISOString(),
      updatedAt: existingPlaylist.updatedAt.toISOString()
    };
  }

  const playlist = await PlaylistModel.create({
    name: playlistName,
    description: `Auto-generated ${config.genre ? config.genre : "mixed"} playlist`,
    userId: null,
    trackIds: tracks.map((track: any) => track._id),
    isPublic: true,
    isAutoGenerated: true,
    generationConfig: config,
    tags: config.genre ? [config.genre] : ["mixed"]
  });

  return {
    id: playlist._id.toString(),
    name: playlist.name,
    description: playlist.description,
    userId: playlist.userId?.toString() || "",
    trackIds: (playlist.trackIds || []).map((id: any) => id.toString()),
    isPublic: playlist.isPublic,
    isAutoGenerated: playlist.isAutoGenerated,
    generationConfig: playlist.generationConfig,
    playCount: playlist.playCount,
    tags: playlist.tags || [],
    createdAt: playlist.createdAt.toISOString(),
    updatedAt: playlist.updatedAt.toISOString()
  };
}
