import { Router } from "express";
import { adminRouter } from "./adminRoutes.js";
import { keywordAdminRouter } from "./keywordAdminRoutes.js";
import { authRouter } from "./authRoutes.js";
import feedRouter from "./feedRoutes.js";
import { healthRouter } from "./healthRoutes.js";
import { interactionRouter } from "./interactionRoutes.js";
import commentRouter from "./commentRoutes.js";
import audioRouter from "./audioRoutes.js";
import profileRouter from "./profileRoutes.js";
import communityRouter from "./communityRoutes.js";
import { communityPostRoutes } from "./communityPostRoutes.js";
import { trendRoutes } from "./trendRoutes.js";
import { failureRouter } from "./failureRoutes.js";
import { auditRouter } from "./auditRoutes.js";
import { embedRouter } from "./embedRoutes.js";
import { notificationRouter } from "./notificationRoutes.js";
import { searchRouter } from "./searchRoutes.js";
import { contentRouter } from "./contentRoutes.js";
import { participativeAIRoutes } from "./participativeAIRoutes.js";
import multiPersonalityAIRoutes from "./multiPersonalityAIRoutes.js";
import { learningProgressRouter } from "./learningProgressRoutes.js";

export const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use("/admin", adminRouter);
apiRouter.use("/admin/keywords", keywordAdminRouter);
apiRouter.use("/feed", feedRouter);
apiRouter.use("/interactions", interactionRouter);
apiRouter.use("/comments", commentRouter);
apiRouter.use("/audio", audioRouter);
apiRouter.use("/community", communityRouter);
apiRouter.use("/community/posts", communityPostRoutes);
apiRouter.use("/profile", profileRouter);
apiRouter.use("/notifications", notificationRouter);
apiRouter.use("/trends", trendRoutes);
apiRouter.use("/failures", failureRouter);
apiRouter.use("/audit", auditRouter);
apiRouter.use("/search", searchRouter);
apiRouter.use("/content", contentRouter);
apiRouter.use("/embed", embedRouter);
apiRouter.use("/ai", participativeAIRoutes);
apiRouter.use("/ai/v2", multiPersonalityAIRoutes);
apiRouter.use("/learning", learningProgressRouter);
apiRouter.use("/", healthRouter);
