import mongoose, { model, Schema } from "mongoose";

const playlistSchema = new Schema(
  {
    name: {
      type: String,
      required: true,
      trim: true
    },
    description: {
      type: String,
      trim: true
    },
    userId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: function(this: any) {
        return !this.isAutoGenerated;
      }
    },
    trackIds: [{
      type: Schema.Types.ObjectId,
      ref: "AudioTrack"
    }],
    isPublic: {
      type: Boolean,
      default: false
    },
    isAutoGenerated: {
      type: Boolean,
      default: false
    },
    generationConfig: {
      type: Schema.Types.Mixed,
      default: null
    },
    playCount: {
      type: Number,
      default: 0
    },
    tags: [{
      type: String,
      trim: true
    }]
  },
  {
    timestamps: true
  }
);

playlistSchema.index({ userId: 1, isPublic: 1 }, { name: "idx_user_public" });
playlistSchema.index({ isAutoGenerated: 1, isPublic: 1 }, { name: "idx_auto_public" });
playlistSchema.index({ playCount: -1 }, { name: "idx_playcount" });
playlistSchema.index({ createdAt: -1 }, { name: "idx_created" });

export const PlaylistModel = mongoose.models.Playlist || model("Playlist", playlistSchema);
