import { motion } from "framer-motion";
import { Playlist } from "../../services/audioService";

interface PlaylistCardProps {
  playlist: Playlist;
  onPlay?: () => void;
  isLoading?: boolean;
}

export function PlaylistCard({ playlist, onPlay, isLoading = false }: PlaylistCardProps) {
  const handlePlay = () => {
    if (onPlay) {
      onPlay();
    }
  };

  const getPlaylistIcon = () => {
    if (playlist.isAutoGenerated) {
      return '\u2728'; // Sparkle for auto-generated
    }
    return '\ud83d\udccb'; // Clipboard for user-created
  };

  const getPlaylistColor = () => {
    if (playlist.isAutoGenerated) {
      return 'bg-gradient-to-br from-purple-500/20 to-blue-500/20 border-purple-500/30';
    }
    return 'bg-gradient-to-br from-gold/20 to-orange-500/20 border-gold/30';
  };

  return (
    <motion.div
      className={`rounded-[1rem] border ${getPlaylistColor()} p-4 cursor-pointer transition-all hover:scale-[1.02]`}
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3 }}
      onClick={handlePlay}
    >
      {/* Header */}
      <div className="flex items-start justify-between mb-3">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 bg-white/10 rounded-lg flex items-center justify-center">
            <span className="text-2xl">{getPlaylistIcon()}</span>
          </div>
          <div className="flex-1">
            <h4 className="text-white font-semibold text-sm">{playlist.name}</h4>
            {playlist.description && (
              <p className="text-sand/70 text-xs mt-1 line-clamp-2">{playlist.description}</p>
            )}
          </div>
        </div>
        
        {playlist.isAutoGenerated && (
          <div className="px-2 py-1 bg-purple-500/20 rounded-full">
            <span className="text-purple-400 text-xs font-medium">Auto</span>
          </div>
        )}
      </div>

      {/* Stats */}
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-4 text-sand/50 text-xs">
          <span>{playlist.trackIds.length} tracks</span>
          <span>{playlist.playCount} plays</span>
        </div>
        
        <div className="flex items-center gap-1">
          {playlist.tags.map((tag, index) => (
            <span
              key={index}
              className="px-2 py-0.5 bg-white/10 text-sand/60 text-xs rounded"
            >
              {tag}
            </span>
          ))}
        </div>
      </div>

      {/* Play Button */}
      <motion.button
        className="w-full py-2 bg-gold/20 hover:bg-gold/30 text-gold rounded-lg text-sm font-medium transition-colors flex items-center justify-center gap-2"
        whileHover={{ scale: 1.02 }}
        whileTap={{ scale: 0.98 }}
        disabled={isLoading}
      >
        {isLoading ? (
          <>
            <div className="w-4 h-4 border-2 border-gold border-t-transparent rounded-full animate-spin" />
            Loading...
          </>
        ) : (
          <>
            <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
              <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM9.555 7.168A1 1 0 008 8v4a1 1 0 001.555.832l3-2a1 1 0 000-1.664l-3-2z"/>
            </svg>
            Play Playlist
          </>
        )}
      </motion.button>

      {/* Metadata */}
      <div className="mt-3 pt-3 border-t border-white/10">
        <p className="text-sand/50 text-xs">
          Created {new Date(playlist.createdAt).toLocaleDateString()}
          {playlist.userId && ' by user'}
        </p>
      </div>
    </motion.div>
  );
}
